---
# tasks file for firefox
- name: "FIREFOX: Setup addons"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "~/.mozilla/extensions/{{ firefox_app_id }}/{{ item.id }}.xpi"
  loop: "{{ firefox_addons }}"