---
- name: "FEDORA: Enable rpmfusion"
  become: true
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  loop:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
  when: enable_rpmfusion

- name: "FEDORA: Install yum packages"
  become: true
  ansible.builtin.yum:
    name: "{{ yum_packages }} + {{ extra_packages }} + {{ common_packages }}"
    state: present
    update_cache: true

- name: "FEDORA: Install pip packages"
  ansible.builtin.pip:
    name: "{{ pip_packages}} + {{ extra_pip_packages }}"
    state: present
...
