- name: "REDHAT Install yum packages"
  become: true
  ansible.builtin.yum:
    name: "{{ yum_packages }} + {{ extra_packages }} + {{ common_packages}}"
    state: present
    update_cache: true

- name: "REDHAT Install pip packages"
  ansible.builtin.pip:
    name: "{{ pip_packages}} + {{ extra_pip_packages }}"
    state: present