---
- name: "UBUNTU: Install deb packages"
  become: true
  ansible.builtin.apt:
    name: "{{ deb_packages }} + {{ extra_packages }} + {{ common_packages }}"
    state: present
    update_cache: true

- name: "UBUNTU: Install pip packages"
  ansible.builtin.pip:
    name: "{{ pip_packages}} + {{ extra_pip_packages }}"
    state: present
...